### ISSUE TITLE
Hovering over certain items throwing LUA errors

### ISSUE THREAD

**Issue by pyebatched** [ZeChrales/AllTheMogs#3]
Hovering over certain items in Classic WotLK causes LUA errors to pop up with the message "Interface/AddOns/AllTheMogs/Database.lua:141: attempt to index field '?' (a nil value)"

Lord Sakrasis' Scepter
Strong Fishing Pole
Big Iron Fishing Pole
Arcanite Fishing Pole
Seth's Graphite Fishing Pole
Blackwood's Thigh
Medicine Stick
Reforged Blade of Heroes
Tunnel Pick
Stitches' Femur
Carving Knife

The full error message below:

Message: Interface/AddOns/AllTheMogs/Database.lua:138: attempt to index field '?' (a nil value)
Time: Tue Apr  9 10:50:24 2024
Count: 6
Stack: Interface/AddOns/AllTheMogs/Database.lua:138: attempt to index field '?' (a nil value)
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/AllTheMogs/Database.lua"]:138: in function `GetItemText'
[string "@Interface/AddOns/AllTheMogs/Tooltip.lua"]:47: in function <Interface/AddOns/AllTheMogs/Tooltip.lua:5>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/TradeSkillMaster/LibTSM/Service/ItemTooltipClasses/Wrapper.lua"]:106: in function <...Master/LibTSM/Service/ItemTooltipClasses/Wrapper.lua:104>
[string "=[C]"]: in function `SetBagItem'
[string "@Interface/FrameXML/ContainerFrame_Shared.lua"]:1362: in function <Interface/FrameXML/ContainerFrame_Shared.lua:1333>
[string "=[C]"]: in function `ContainerFrameItemButton_OnEnter'
[string "*ContainerFrame.xml:184_OnEnter"]:1: in function <[string "*ContainerFrame.xml:184_OnEnter"]:1>

Locals: (*temporary) = true
(*temporary) = <function> defined =[C]:-1

**Comment by ZeChrales** [comment]
Fixed by 82628b47103b168d1ac3b9b86fa6913a8d31d9ec in next version !
